USE MariaCamilaPasteleria;

-- ROLE ADMINISTRADOR
DROP ROLE IF EXISTS ADMINISTRADOR;
CREATE ROLE ADMINISTRADOR;
GRANT ALL PRIVILEGES ON MariaCamilaPasteleria.* TO ADMINISTRADOR;
SHOW GRANTS FOR ADMINISTRADOR;

CREATE USER IF NOT EXISTS 'Mariacamila'@'localhost' IDENTIFIED BY 'pasteleria';

GRANT ADMINISTRADOR TO 'Mariacamila'@'localhost';
SET DEFAULT ROLE ADMINISTRADOR TO 'Mariacamila'@'localhost'; 
SHOW GRANTS FOR 'Mariacamila'@'localhost';

-- ROLE CLIENTE 
DROP ROLE IF EXISTS CLIENTE;
CREATE ROLE CLIENTE;
GRANT SELECT ON MariaCamilaPasteleria.* TO CLIENTE;
GRANT SELECT ON vw_cupcake TO CLIENTE;
GRANT SELECT ON vw_ancheta TO CLIENTE;
GRANT SELECT ON vw_ponque TO CLIENTE;
GRANT CREATE, SELECT, INSERT ON vw_pedido TO CLIENTE;
GRANT CREATE, SELECT, UPDATE ON vw_pedido_producto TO CLIENTE;
GRANT ALL ON vw_comentario TO CLIENTE;


-- PERMISOS EN PAS Y FUNCIONES
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_CLIENTE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_ACTUALIZAR_CLIENTE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_CREAR_CLIENTE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_BORRAR_CLIENTE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_ANCHETA_NOMBRE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_ANCHETA_PRECIO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_ANCHETA_MOTIVO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_CUPCAKE_NOMBRE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_CUPCAKE_PRECIO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_CUPCAKE_MOTIVO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_CUPCAKE_SABOR TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PONQUE_NOMBRE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PONQUE_PRECIO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PONQUE_MOTIVO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PONQUE_SABOR TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PONQUE_PORCIONES TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDO_ID_PEDIDO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDOS_ID_CLIENTE TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDO_FECHA_CREACION TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDO_FECHA_ENTREGA TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDO_COSTO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDO_ESTADO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_BORRAR_PEDIDO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_BORRAR_PEDIDO_PRODUCTO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDO_PRODUCTO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_COMENTARIO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_CREACION_COMENTARIO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_ACTUALIZAR_COMENTARIO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_BORRAR_COMENTARIO TO CLIENTE;
GRANT EXECUTE ON FUNCTION MariaCamilaPasteleria.TOTAL_PEDIDO_PRODUCTO TO CLIENTE;
GRANT EXECUTE ON FUNCTION MariaCamilaPasteleria.TOTAL_PEDIDO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_CREACION_PEDIDO_PRODUCTO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_CREACION_PEDIDO TO CLIENTE;
GRANT EXECUTE ON PROCEDURE MariaCamilaPasteleria.CLIENTE_VISTA_PEDIDOS_GENERAL TO CLIENTE;
GRANT EXECUTE ON FUNCTION MariaCamilaPasteleria.NUMERO_PEDIDOS TO CLIENTE;

SHOW GRANTS FOR CLIENTE;

CREATE USER IF NOT EXISTS 'Usuario'@'localhost' IDENTIFIED BY '12345';
GRANT CLIENTE TO 'Usuario'@'localhost';
SET DEFAULT ROLE CLIENTE TO 'Usuario'@'localhost'; 
SHOW GRANTS FOR 'Usuario'@'localhost';